FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# blog

Blog is a simple to do app that allows creating todos and items within.

## Questions Collection [/todo]

### List All Todos [GET]

+ Response 200 (application/json)

        {
            "status": "success",
                "data": [
                {
                    "name": "Sing",
                    "date_created": "2018-05-19 10:32:51.134777"
                },
                {
                    "name": "Dance",
                    "date_created": "date_created": "2018-06-20 17:47:49.040776"
                }
            ]
        }

### Create a New Todo [POST]

You may create a new todo using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "name": "Mountain Climbing"
        }

+ Response 201 (application/json)

    + Headers

    + Body

            {
                "status": "success",
                "data" :{
                    "date_created": "2018-06-20 17:47:49.040776",
                    "name": "dancing"
                }
            }